# Main configuration
url: https://docs.rusic.com
title: Rusic Documentation
description: Official documentation for Rusic
repository: https://github.com/rusic/documentation

# Site details
twitter: rusichq

# Jekyll options
exclude:
- CNAME
- LICENSE
- README.md
- bower_components
- bower.json
- gulpfile.js
- node_modules
- package.json

highlighter: pygments

markdown: kramdown

excerpt_separator: "\n\n"

# Permalinks
permalink: pretty

# Gems
gems:
- jemoji
- jekyll-sitemap

# Sass options
sass:
  style: compressed
